### ISSUE TITLE
Adaptive

### ISSUE THREAD

**Issue by VeryOldLady** [BESTLviv/EBEC_web#5]
Сделать обрезку бекграунда по центру и кнопка на должна наезжать на лого EBEC Challenge (там вообще должен быть отсутп в толщину одного выступа шестерни (одной из тех 5-ти фиговин)

**Comment by Monstrofil** [comment]
![image](https://user-images.githubusercontent.com/8678392/32142941-beb263d0-bcaa-11e7-9760-db1ecec82a25.png)
check pls

**Comment by VeryOldLady** [comment]
![issue](https://user-images.githubusercontent.com/31952081/32166969-2cc2888a-bd70-11e7-9dc2-d4eea9d92ff0.png)

**Comment by Monstrofil** [comment]
![image](https://user-images.githubusercontent.com/8678392/32181841-05377c5c-bd9e-11e7-8765-99952f6d25a2.png)

**Comment by Monstrofil** [comment]
прибил фон к верху
